name: "LLM Version Alert"
description: "Checks for new LLM model releases and sends alerts for OpenAI GPT models."
author: "dhananjaypai"
branding:
  icon: "bell"
  color: "blue"

inputs:
  source:
    description: "LLM provider to check (currently supports: openai)"
    required: true
    default: "openai"
  openai_api_key:
    description: "OpenAI API key for authentication"
    required: true
  notify:
    description: "Notification mode: none|issue|fail (issue creates/updates an issue; fail exits non-zero on change)"
    required: false
    default: "none"
  manifest_file:
    description: "File to write latest model id into (for PR/visibility). Empty to disable."
    required: false
    default: "LATEST_LLM_MODEL.txt"

outputs:
  model_detected:
    description: "The latest model detected"
  version_changed:
    description: "Whether a new version was detected (true/false)"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      shell: bash
      run: |
        python3 --version
        pip install requests python-dotenv

    - name: Run LLM version check
      id: check
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        NOTIFY_MODE: ${{ inputs.notify }}
        MANIFEST_FILE: ${{ inputs.manifest_file }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python3 ${{ github.action_path }}/check_llm.py "${{ inputs.source }}"
