name: "LLM Version Alert"
description: "🚨 Automatically checks for new LLM model releases and sends alerts. Supports OpenAI GPT models with plans for Claude, Gemini, and more."
author: "dhananjaypai"
branding:
  icon: "bell"
  color: "blue"

inputs:
  source:
    description: "LLM provider to check (currently supports: openai)"
    required: true
    default: "openai"

outputs:
  model_detected:
    description: "The latest model detected"
  version_changed:
    description: "Whether a new version was detected (true/false)"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      shell: bash
      run: |
        python3 --version
        pip install requests python-dotenv

    - name: Run LLM version check
      id: check
      shell: bash
      env:
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
      run: |
        python3 ${{ github.action_path }}/check_llm.py "${{ inputs.source }}"
